apiVersion: v1
kind: Service
metadata:
  name: digital-ocean-kubernetes
  labels:
    app: digital-ocean-kubernetes
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: digital-ocean-kubernetes